version: "1"

services:
  postgres:
    image: 'postgres:13'
    container_name: 'reg_auth'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'
